# 
#Copyright (c) 2021, Alibaba Group;
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.
#

version: 1.0
type: homogeneous
dispatcher:
  - type: e906
regular:
  - type: e906
rvcluster: # rv cluster topology
  num: 3
  config: ["dispatcher", "regular_0", "regular_1"]
  dispatcher: 
    - name: dispatcher 
      link:
      - dst: regular_0
        index: 0
        qid: 0
        type: xocc
        width: [32, 32] # cmd width, rsp width; depth is fixed to 32
      - dst: regular_1
        index: 1
        qid: 1
        type: xocc
        width: [32, 32]
      - dst: nou
        index: 2
        qid: 2
        type: xocc
        width: [64, 64]
      - dst: dsa_2
        index: 3
        qid: 3
        type: xocc
        width: [32, 32]
      - dst: memory
        type: axi
        index: 0
        width: 32
        mem:
      toolchain:
        imem_s_addr: 0x02000000
        imem_range: 0x20000
        dmem_s_addr: 0x02020000
        dmem_range: 0x20000
        stack_addr: 0x0203c000
  regular:
    - name: regular_0
      link:
      - dst: dispatcher
        index: 0
        qid: 0
        type: xocc
        width: [32, 32]
      - dst: dsa_0
        index: 4
        qid: 1
        type: xocc
        width: [96, 32]
      - dst: memory
        index: 1
        type: axi
        width: 32
        mem:
      toolchain:
        imem_s_addr: 0x02100000
        imem_range: 0x20000
        dmem_s_addr: 0x02120000
        dmem_range: 0x20000
        stack_addr: 0x0213c000
    - name: regular_1
      link:
      - dst: dispatcher
        index: 1
        qid: 0
        type: xocc
        width: [32, 32]
      - dst: dsa_1
        index: 5
        qid: 1
        type: xocc
        width: [32, 32]
      - dst: memory
        index: 2
        type: axi
        width: 32
        mem:
      toolchain:
        imem_s_addr: 0x02200000
        imem_range: 0x20000
        dmem_s_addr: 0x02220000
        dmem_range: 0x20000
        stack_addr: 0x0223c000
memory:
- size: 524288 # unit: Byte
  type: scratchpad # or 3DMem
  bankNum: 4
  index: 0
  memory_map:
    - name: sram_0
      start_addr: 32'h0200_0000
      end_addr: 32'h0210_0000
    - name: sram_1
      start_addr: 32'h0210_0000
      end_addr: 32'h0220_0000
    - name: sram_2
      start_addr: 32'h0220_0000
      end_addr: 32'h0230_0000
    - name: sram_3
      start_addr: 32'h0230_0000
      end_addr: 32'h0240_0000
- size: 4096
  type: csr
  bankNum:
  index: 1
  memory_map:
    - name: csr
      start_addr: 32'hc000_0000
      end_addr: 32'hc010_0000
dsa:  # dsa topology, xocc port is ignored
  num: 2
  config: ["dsa_0", "dsa_1", "dsa_2", "nou"]
  dummy_dsa:
    - name: dsa_0
      link:
      - dst: memory
        index: 3
        type: axi
        width: 1024
        port: rw
        mem:
      - dst: regular_0
        index: 4
        type: xocc
    - name: dsa_1
      link:
      - dst: memory
        index: 4
        type: axi
        width: 1024
        port: rw
        mem:
      - dst: regular_1
        index: 5
        type: xocc
    - name: dsa_2
      link:
      - dst: memory
        index: 5
        type: axi
        width: 1024
        port: rw
        mem:
      - dst: dispatcher
        index: 3
        type: xocc
  nou:
    - name: nou
      link:
      - dst: memory
        index: 6
        type: axi
        width: 512
        port: rw
        mem:
      - dst: noc_0
        index: 0
        type: noc
        width: 512
        mem:
      - dst: dispatcher
        index: 2
        type: xocc
