# 
#Copyright (c) 2021, Alibaba Group;
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.
#

version: 1.0
type: homogeneous
topology: [4,4]
link:
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 1
  index: 16
  isBusy: false
  latency: 1
  src: 0
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 4
  index: 17
  isBusy: false
  latency: 1
  src: 0
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 2
  index: 18
  isBusy: false
  latency: 1
  src: 1
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 5
  index: 19
  isBusy: false
  latency: 1
  src: 1
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 3
  index: 20
  isBusy: false
  latency: 1
  src: 2
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 6
  index: 21
  isBusy: false
  latency: 1
  src: 2
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 7
  index: 22
  isBusy: false
  latency: 1
  src: 3
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 5
  index: 23
  isBusy: false
  latency: 1
  src: 4
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 8
  index: 24
  isBusy: false
  latency: 1
  src: 4
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 6
  index: 25
  isBusy: false
  latency: 1
  src: 5
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 9
  index: 26
  isBusy: false
  latency: 1
  src: 5
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 7
  index: 27
  isBusy: false
  latency: 1
  src: 6
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 10
  index: 28
  isBusy: false
  latency: 1
  src: 6
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 11
  index: 29
  isBusy: false
  latency: 1
  src: 7
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 9
  index: 30
  isBusy: false
  latency: 1
  src: 8
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 12
  index: 31
  isBusy: false
  latency: 1
  src: 8
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 10
  index: 32
  isBusy: false
  latency: 1
  src: 9
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 13
  index: 33
  isBusy: false
  latency: 1
  src: 9
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 11
  index: 34
  isBusy: false
  latency: 1
  src: 10
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 14
  index: 35
  isBusy: false
  latency: 1
  src: 10
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 15
  index: 36
  isBusy: false
  latency: 1
  src: 11
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 13
  index: 37
  isBusy: false
  latency: 1
  src: 12
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 14
  index: 38
  isBusy: false
  latency: 1
  src: 13
- bandwidth: 128
  currentBandwidth: 0.0
  direction: bi
  dst: 15
  index: 39
  isBusy: false
  latency: 1
  src: 14
memory:
- currentData: []
  index: -1
  memSize: 0
pe:
- computeCapacityTensor: 1024
  computeCapacityVector: 32
  currentMem: 0
  currentOpIndex: -1
  index: 0
  isBusy: false
  memSize: 524288
  name: thrive_pe_0_0
  type: thrive_pe
  x: 0
  y: 0
- computeCapacityTensor: 1024
  computeCapacityVector: 32
  currentMem: 0
  currentOpIndex: -1
  index: 1
  isBusy: false
  memSize: 524288
  name: thrive_pe_1_0
  type: thrive_pe
  x: 1
  y: 0
- computeCapacityTensor: 1024
  computeCapacityVector: 32
  currentMem: 0
  currentOpIndex: -1
  index: 2
  isBusy: false
  memSize: 524288
  name: thrive_pe_2_0
  type: thrive_pe
  x: 2
  y: 0
- computeCapacityTensor: 1024
  computeCapacityVector: 32
  currentMem: 0
  currentOpIndex: -1
  index: 3
  isBusy: false
  memSize: 524288
  name: thrive_pe_3_0
  type: thrive_pe
  x: 3
  y: 0
- computeCapacityTensor: 1024
  computeCapacityVector: 32
  currentMem: 0
  currentOpIndex: -1
  index: 4
  isBusy: false
  memSize: 524288
  name: thrive_pe_0_1
  type: thrive_pe
  x: 0
  y: 1
- computeCapacityTensor: 1024
  computeCapacityVector: 32
  currentMem: 0
  currentOpIndex: -1
  index: 5
  isBusy: false
  memSize: 524288
  name: thrive_pe_1_1
  type: thrive_pe
  x: 1
  y: 1
- computeCapacityTensor: 1024
  computeCapacityVector: 32
  currentMem: 0
  currentOpIndex: -1
  index: 6
  isBusy: false
  memSize: 524288
  name: thrive_pe_2_1
  type: thrive_pe
  x: 2
  y: 1
- computeCapacityTensor: 1024
  computeCapacityVector: 32
  currentMem: 0
  currentOpIndex: -1
  index: 7
  isBusy: false
  memSize: 524288
  name: thrive_pe_3_1
  type: thrive_pe
  x: 3
  y: 1
- computeCapacityTensor: 1024
  computeCapacityVector: 32
  currentMem: 0
  currentOpIndex: -1
  index: 8
  isBusy: false
  memSize: 524288
  name: thrive_pe_0_2
  type: thrive_pe
  x: 0
  y: 2
- computeCapacityTensor: 1024
  computeCapacityVector: 32
  currentMem: 0
  currentOpIndex: -1
  index: 9
  isBusy: false
  memSize: 524288
  name: thrive_pe_1_2
  type: thrive_pe
  x: 1
  y: 2
- computeCapacityTensor: 1024
  computeCapacityVector: 32
  currentMem: 0
  currentOpIndex: -1
  index: 10
  isBusy: false
  memSize: 524288
  name: thrive_pe_2_2
  type: thrive_pe
  x: 2
  y: 2
- computeCapacityTensor: 1024
  computeCapacityVector: 32
  currentMem: 0
  currentOpIndex: -1
  index: 11
  isBusy: false
  memSize: 524288
  name: thrive_pe_3_2
  type: thrive_pe
  x: 3
  y: 2
- computeCapacityTensor: 1024
  computeCapacityVector: 32
  currentMem: 0
  currentOpIndex: -1
  index: 12
  isBusy: false
  memSize: 524288
  name: thrive_pe_0_3
  type: thrive_pe
  x: 0
  y: 3
- computeCapacityTensor: 1024
  computeCapacityVector: 32
  currentMem: 0
  currentOpIndex: -1
  index: 13
  isBusy: false
  memSize: 524288
  name: thrive_pe_1_3
  type: thrive_pe
  x: 1
  y: 3
- computeCapacityTensor: 1024
  computeCapacityVector: 32
  currentMem: 0
  currentOpIndex: -1
  index: 14
  isBusy: false
  memSize: 524288
  name: thrive_pe_2_3
  type: thrive_pe
  x: 2
  y: 3
- computeCapacityTensor: 1024
  computeCapacityVector: 32
  currentMem: 0
  currentOpIndex: -1
  index: 15
  isBusy: false
  memSize: 524288
  name: thrive_pe_3_3
  type: thrive_pe
  x: 3
  y: 3