/* 
*Copyright (c) 2021, Alibaba Group;
*Licensed under the Apache License, Version 2.0 (the "License");
*you may not use this file except in compliance with the License.
*You may obtain a copy of the License at

*   http://www.apache.org/licenses/LICENSE-2.0

*Unless required by applicable law or agreed to in writing, software
*distributed under the License is distributed on an "AS IS" BASIS,
*WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*See the License for the specific language governing permissions and
*limitations under the License.
*/

$DESIGN_SRC/cpu/cpu/rtl/cpu_cfig.h
$DESIGN_SRC/cpu/dtu/rtl/pa_dtu_cfig.h
$DESIGN_SRC/cpu/idu/rtl/pa_idu_cfig.h
$DESIGN_SRC/cpu/tdt/rtl/top/tdt_define.h
$DESIGN_SRC/cpu/sysmap/rtl/sysmap.h
$DESIGN_SRC/cpu/cpu/rtl/xocc_define.h
+incdir+$DESIGN_SRC/cpu/cpu/rtl+$DESIGN_SRC/cpu/dtu/rtl+$DESIGN_SRC/cpu/idu/rtl+$DESIGN_SRC/cpu/tdt/rtl/top+$DESIGN_SRC/cpu/sysmap/rtl
$DESIGN_SRC/cpu/cpu_ss/system/dispatcher_rv_wrapper.v
$DESIGN_SRC/cpu/cpu_ss/system/regular_0_rv_wrapper.v
$DESIGN_SRC/cpu/cpu_ss/system/regular_1_rv_wrapper.v
$DESIGN_SRC/cpu/cpu_ss/system/regular_2_rv_wrapper.v
$DESIGN_SRC/cpu/common/rtl/BUFGCE.v
$DESIGN_SRC/cpu/fmau/rtl/booth_code_25_bit.v
$DESIGN_SRC/cpu/iu/rtl/booth_code_33_bit.v
$DESIGN_SRC/cpu/clk/rtl/gated_clk_cell.v
$DESIGN_SRC/cpu/iu/rtl/multiplier_33x33_partial.v
$DESIGN_SRC/cpu/biu/rtl/pa_ahbl_if.v
$DESIGN_SRC/cpu/biu/rtl/pa_ahbl_if_fo.v
$DESIGN_SRC/cpu/bmu/rtl/pa_bmu_bus_if.v
$DESIGN_SRC/cpu/bmu/rtl/pa_bmu_dbus_if.v
$DESIGN_SRC/cpu/bmu/rtl/pa_bmu_top.v
$DESIGN_SRC/cpu/clic/rtl/pa_clic_arb.v
$DESIGN_SRC/cpu/clic/rtl/pa_clic_arb_32to1_kernel.v
$DESIGN_SRC/cpu/clic/rtl/pa_clic_arb_kernel.v
$DESIGN_SRC/cpu/clic/rtl/pa_clic_busif.v
$DESIGN_SRC/cpu/clic/rtl/pa_clic_cpuif_2cycle.v
$DESIGN_SRC/cpu/clic/rtl/pa_clic_ctrl.v
$DESIGN_SRC/cpu/clic/rtl/pa_clic_expand.v
$DESIGN_SRC/cpu/clic/rtl/pa_clic_ff1_onehot.v
$DESIGN_SRC/cpu/clic/rtl/pa_clic_kid.v
$DESIGN_SRC/cpu/clic/rtl/pa_clic_kid_dummy.v
$DESIGN_SRC/cpu/clic/rtl/pa_clic_sel.v
$DESIGN_SRC/cpu/clic/rtl/pa_clic_top.v
$DESIGN_SRC/cpu/clint/rtl/pa_clint_busif.v
$DESIGN_SRC/cpu/clint/rtl/pa_clint_regs.v
$DESIGN_SRC/cpu/clint/rtl/pa_clint_top.v
$DESIGN_SRC/cpu/clk/rtl/pa_clk_top.v
$DESIGN_SRC/cpu/clk/rtl/pa_clkrst_top.v
$DESIGN_SRC/cpu/cp0/rtl/pa_cp0_ext_csr.v
$DESIGN_SRC/cpu/cp0/rtl/pa_cp0_ext_inst.v
$DESIGN_SRC/cpu/cp0/rtl/pa_cp0_float_csr.v
$DESIGN_SRC/cpu/cp0/rtl/pa_cp0_info_csr.v
$DESIGN_SRC/cpu/cp0/rtl/pa_cp0_iui.v
$DESIGN_SRC/cpu/cp0/rtl/pa_cp0_regs.v
$DESIGN_SRC/cpu/cp0/rtl/pa_cp0_special.v
$DESIGN_SRC/cpu/cp0/rtl/pa_cp0_srst.v
$DESIGN_SRC/cpu/cp0/rtl/pa_cp0_top.v
$DESIGN_SRC/cpu/cp0/rtl/pa_cp0_trap_csr.v
$DESIGN_SRC/cpu/cpu/rtl/pa_cpu_top_golden_port.v
$DESIGN_SRC/cpu/biu/rtl/pa_dahbl_top.v
$DESIGN_SRC/cpu/lsu/rtl/pa_dcache_data_array.v
$DESIGN_SRC/cpu/lsu/rtl/pa_dcache_dirty_array.v
$DESIGN_SRC/cpu/lsu/rtl/pa_dcache_tag_array.v
$DESIGN_SRC/cpu/lsu/rtl/pa_dcache_top.v
$DESIGN_SRC/cpu/dtu/rtl/pa_dtu_cdc.v
$DESIGN_SRC/cpu/dtu/rtl/pa_dtu_cdc_lvl.v
$DESIGN_SRC/cpu/dtu/rtl/pa_dtu_cdc_pulse.v
$DESIGN_SRC/cpu/dtu/rtl/pa_dtu_ctrl.v
$DESIGN_SRC/cpu/dtu/rtl/pa_dtu_dbginfo.v
$DESIGN_SRC/cpu/dtu/rtl/pa_dtu_m_iie_all.v
$DESIGN_SRC/cpu/dtu/rtl/pa_dtu_mcontrol_0.v
$DESIGN_SRC/cpu/dtu/rtl/pa_dtu_mcontrol_1.v
$DESIGN_SRC/cpu/dtu/rtl/pa_dtu_mcontrol_2.v
$DESIGN_SRC/cpu/dtu/rtl/pa_dtu_mcontrol_output_select.v
$DESIGN_SRC/cpu/dtu/rtl/pa_dtu_pcfifo.v
$DESIGN_SRC/cpu/dtu/rtl/pa_dtu_top.v
$DESIGN_SRC/cpu/dtu/rtl/pa_dtu_trigger_module.v
$DESIGN_SRC/cpu/fpga/rtl/fpga_ram.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_1024x32.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_1024x36.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_1024x37.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_1024x4.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_128x32.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_128x4.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_128x42.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_128x43.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_2048x32.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_256x32.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_256x4.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_256x40.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_256x41.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_32x4.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_32x46.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_32x47.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_4096x32.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_512x16.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_512x32.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_512x38.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_512x39.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_512x4.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_64x4.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_64x44.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_64x45.v
$DESIGN_SRC/cpu/fpga/rtl/pa_f_spsram_8192x32.v
$DESIGN_SRC/cpu/falu/rtl/pa_fadd_lop_s1_s.v
$DESIGN_SRC/cpu/falu/rtl/pa_fadd_nm_shift_single.v
$DESIGN_SRC/cpu/falu/rtl/pa_fadd_shift_sub_single.v
$DESIGN_SRC/cpu/falu/rtl/pa_fadd_single.v
$DESIGN_SRC/cpu/falu/rtl/pa_falu_ctrl.v
$DESIGN_SRC/cpu/falu/rtl/pa_falu_top.v
$DESIGN_SRC/cpu/falu/rtl/pa_fcnvt_ftoi_s.v
$DESIGN_SRC/cpu/falu/rtl/pa_fcnvt_itof_s.v
$DESIGN_SRC/cpu/falu/rtl/pa_fcnvt_single.v
$DESIGN_SRC/cpu/fdsu/rtl/pa_fdsu_ctrl.v
$DESIGN_SRC/cpu/fdsu/rtl/pa_fdsu_ff1.v
$DESIGN_SRC/cpu/fdsu/rtl/pa_fdsu_pack_single.v
$DESIGN_SRC/cpu/fdsu/rtl/pa_fdsu_prepare.v
$DESIGN_SRC/cpu/fdsu/rtl/pa_fdsu_round_single.v
$DESIGN_SRC/cpu/fdsu/rtl/pa_fdsu_special.v
$DESIGN_SRC/cpu/fdsu/rtl/pa_fdsu_srt_single.v
$DESIGN_SRC/cpu/fdsu/rtl/pa_fdsu_top.v
$DESIGN_SRC/cpu/fmau/rtl/pa_fmau_ctrl.v
$DESIGN_SRC/cpu/fmau/rtl/pa_fmau_dp.v
$DESIGN_SRC/cpu/fmau/rtl/pa_fmau_ex1_special_judge.v
$DESIGN_SRC/cpu/fmau/rtl/pa_fmau_frac_add.v
$DESIGN_SRC/cpu/fmau/rtl/pa_fmau_frac_mult.v
$DESIGN_SRC/cpu/fmau/rtl/pa_fmau_frac_shift.v
$DESIGN_SRC/cpu/fmau/rtl/pa_fmau_lza_single.v
$DESIGN_SRC/cpu/fmau/rtl/pa_fmau_multiplier_24x24_partial.v
$DESIGN_SRC/cpu/fmau/rtl/pa_fmau_src2_shifter_single.v
$DESIGN_SRC/cpu/fmau/rtl/pa_fmau_top.v
$DESIGN_SRC/cpu/fpu/rtl/pa_fpu_ctrl.v
$DESIGN_SRC/cpu/fpu/rtl/pa_fpu_dp.v
$DESIGN_SRC/cpu/fpu/rtl/pa_fpu_frbus.v
$DESIGN_SRC/cpu/fpu/rtl/pa_fpu_src_type.v
$DESIGN_SRC/cpu/fpu/rtl/pa_fpu_top.v
$DESIGN_SRC/cpu/falu/rtl/pa_fspu_single.v
$DESIGN_SRC/cpu/pmu/rtl/pa_hpcp_cnt.v
$DESIGN_SRC/cpu/pmu/rtl/pa_hpcp_event.v
$DESIGN_SRC/cpu/pmu/rtl/pa_hpcp_top.v
$DESIGN_SRC/cpu/biu/rtl/pa_iahbl_top.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_ctrl.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_decd_dsp.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_decd_fp.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_decd_rv32c.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_decd_rv32fd.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_decd_rv32im.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_decd_rv32x.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_dp.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_fpr.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_gpr.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_hs.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_id_fp.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_reg.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_reg32.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_reg32_high.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_reg_sp.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_split.v
$DESIGN_SRC/cpu/idu/rtl/pa_idu_top.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_bht.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_bht_array.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_btb.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_btb_entry.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_ctrl.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_ibuf.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_ibuf_entry.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_ibuf_pop_entry.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_icache.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_icache_data_array.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_icache_tag_array.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_id_pred.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_ifetch.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_ipack.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_ipack_entry.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_pcgen.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_pre_decd.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_ras.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_ras_entry.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_top.v
$DESIGN_SRC/cpu/ifu/rtl/pa_ifu_vec.v
$DESIGN_SRC/cpu/iu/rtl/pa_iu_addr_gen.v
$DESIGN_SRC/cpu/iu/rtl/pa_iu_alu.v
$DESIGN_SRC/cpu/iu/rtl/pa_iu_bju.v
$DESIGN_SRC/cpu/iu/rtl/pa_iu_ctrl.v
$DESIGN_SRC/cpu/iu/rtl/pa_iu_div.v
$DESIGN_SRC/cpu/iu/rtl/pa_iu_div_shift2_kernel.v
$DESIGN_SRC/cpu/iu/rtl/pa_iu_mul.v
$DESIGN_SRC/cpu/iu/rtl/pa_iu_top.v
$DESIGN_SRC/cpu/lsu/rtl/pa_lsu_ag.v
$DESIGN_SRC/cpu/lsu/rtl/pa_lsu_arb.v
$DESIGN_SRC/cpu/lsu/rtl/pa_lsu_dahbif.v
$DESIGN_SRC/cpu/lsu/rtl/pa_lsu_dc.v
$DESIGN_SRC/cpu/lsu/rtl/pa_lsu_dtif.v
$DESIGN_SRC/cpu/lsu/rtl/pa_lsu_icc.v
$DESIGN_SRC/cpu/lsu/rtl/pa_lsu_lfb.v
$DESIGN_SRC/cpu/lsu/rtl/pa_lsu_lm.v
$DESIGN_SRC/cpu/lsu/rtl/pa_lsu_ncb.v
$DESIGN_SRC/cpu/lsu/rtl/pa_lsu_rdl.v
$DESIGN_SRC/cpu/lsu/rtl/pa_lsu_stb.v
$DESIGN_SRC/cpu/lsu/rtl/pa_lsu_stb_entry.v
$DESIGN_SRC/cpu/lsu/rtl/pa_lsu_top.v
$DESIGN_SRC/cpu/lsu/rtl/pa_lsu_vb.v
$DESIGN_SRC/cpu/lsu/rtl/pa_lsu_vb_entry.v
$DESIGN_SRC/cpu/lsu/rtl/pa_lsu_wb_entry.v
$DESIGN_SRC/cpu/pmp/rtl/pa_pmp_acc_arb.v
$DESIGN_SRC/cpu/pmp/rtl/pa_pmp_comp_hit.v
$DESIGN_SRC/cpu/pmp/rtl/pa_pmp_enc.v
$DESIGN_SRC/cpu/pmp/rtl/pa_pmp_regs.v
$DESIGN_SRC/cpu/pmp/rtl/pa_pmp_top.v
$DESIGN_SRC/cpu/rst/rtl/pa_rst_top.v
$DESIGN_SRC/cpu/rtu/rtl/pa_rtu_cbus.v
$DESIGN_SRC/cpu/rtu/rtl/pa_rtu_int.v
$DESIGN_SRC/cpu/rtu/rtl/pa_rtu_lockup.v
$DESIGN_SRC/cpu/rtu/rtl/pa_rtu_rbus.v
$DESIGN_SRC/cpu/rtu/rtl/pa_rtu_retire.v
$DESIGN_SRC/cpu/rtu/rtl/pa_rtu_top.v
$DESIGN_SRC/cpu/biu/rtl/pa_sahbl_top.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_1024x32.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_1024x36.v
$DESIGN_SRC/cpu/ifu/rtl/pa_spsram_1024x37.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_1024x4.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_128x32.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_128x4.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_128x42.v
$DESIGN_SRC/cpu/ifu/rtl/pa_spsram_128x43.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_2048x32.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_256x32.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_256x4.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_256x40.v
$DESIGN_SRC/cpu/ifu/rtl/pa_spsram_256x41.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_32x4.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_32x46.v
$DESIGN_SRC/cpu/ifu/rtl/pa_spsram_32x47.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_4096x32.v
$DESIGN_SRC/cpu/ifu/rtl/pa_spsram_512x16.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_512x32.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_512x38.v
$DESIGN_SRC/cpu/ifu/rtl/pa_spsram_512x39.v
$DESIGN_SRC/cpu/ifu/rtl/pa_spsram_512x4.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_64x4.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_64x44.v
$DESIGN_SRC/cpu/ifu/rtl/pa_spsram_64x45.v
$DESIGN_SRC/cpu/lsu/rtl/pa_spsram_8192x32.v
$DESIGN_SRC/cpu/cpu/rtl/pa_sys_io.v
$DESIGN_SRC/cpu/sysmap/rtl/pa_sysmap_access.v
$DESIGN_SRC/cpu/sysmap/rtl/pa_sysmap_busif.v
$DESIGN_SRC/cpu/sysmap/rtl/pa_sysmap_hit.v
$DESIGN_SRC/cpu/sysmap/rtl/pa_sysmap_reg.v
$DESIGN_SRC/cpu/sysmap/rtl/pa_sysmap_top.v
$DESIGN_SRC/cpu/tcipif/rtl/pa_tcipif_behavior_bus.v
$DESIGN_SRC/cpu/tcipif/rtl/pa_tcipif_dummy_bus.v
$DESIGN_SRC/cpu/tcipif/rtl/pa_tcipif_top.v
$DESIGN_SRC/cpu/tdt/rtl/debug/tdt_dm.v
$DESIGN_SRC/cpu/tdt/rtl/top/tdt_dm_top.v
$DESIGN_SRC/cpu/tdt/rtl/top/tdt_top.v
$DESIGN_SRC/cpu/cpu/rtl/dispatcher_pa_core_top.v
$DESIGN_SRC/cpu/cpu/rtl/dispatcher_pa_core.v
$DESIGN_SRC/cpu/cpu/rtl/dispatcher_pa_cpu_top.v
$DESIGN_SRC/cpu/cpu/rtl/regular_0_pa_core_top.v
$DESIGN_SRC/cpu/cpu/rtl/regular_0_pa_core.v
$DESIGN_SRC/cpu/cpu/rtl/regular_0_pa_cpu_top.v
$DESIGN_SRC/cpu/cpu/rtl/regular_1_pa_core_top.v
$DESIGN_SRC/cpu/cpu/rtl/regular_1_pa_core.v
$DESIGN_SRC/cpu/cpu/rtl/regular_1_pa_cpu_top.v
$DESIGN_SRC/cpu/cpu/rtl/regular_2_pa_core_top.v
$DESIGN_SRC/cpu/cpu/rtl/regular_2_pa_core.v
$DESIGN_SRC/cpu/cpu/rtl/regular_2_pa_cpu_top.v
$DESIGN_SRC/cpu/cpu_ss/system/dispatcher_cpu_sub_system_ahb.v
$DESIGN_SRC/cpu/cpu_ss/system/regular_0_cpu_sub_system_ahb.v
$DESIGN_SRC/cpu/cpu_ss/system/regular_1_cpu_sub_system_ahb.v
$DESIGN_SRC/cpu/cpu_ss/system/regular_2_cpu_sub_system_ahb.v
$DESIGN_SRC/cpu/iu/rtl/dispatcher_pa_iu_top.v
$DESIGN_SRC/cpu/iu/rtl/regular_0_pa_iu_top.v
$DESIGN_SRC/cpu/iu/rtl/regular_1_pa_iu_top.v
$DESIGN_SRC/cpu/iu/rtl/regular_2_pa_iu_top.v
$DESIGN_SRC/cpu/iu/rtl/dispatcher_pa_iu_xocc.v
$DESIGN_SRC/cpu/iu/rtl/regular_0_pa_iu_xocc.v
$DESIGN_SRC/cpu/iu/rtl/regular_1_pa_iu_xocc.v
$DESIGN_SRC/cpu/iu/rtl/regular_2_pa_iu_xocc.v
