# 
#Copyright (c) 2021, Alibaba Group;
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.
#

gen_pe_hetero:
	vmake -depend
	vmake pe_0_0_pe_top.v
	vmake pe_0_1_pe_top.v
	vmake pe_1_0_pe_top.v
	vmake pe_1_1_pe_top.v

gen_pe_homo:
	vmake -depend
	vmake pe_0_0_pe_top.v